import './style.css';

const booking = 'https://forms.gle/yNfGFLgHMPCdd7x48';
const airbnb = 'http://airbnb.ie/h/countrybeachescape';
const nav = [['/the-house','The House'],['/faq','FAQ'],['/calendar','Calendar'],['/gallery','Gallery'],['/to-do','To Do'],['/contact-us','Contact Us'],['/owner','Owner']];
const gallery = [
 'https://lh3.googleusercontent.com/sitesv/AG8ngQUntIhk43j0i1M9yqr1_g_9A3zEGfFY1cwLEg-MRhtKvoAs8ZWIe4Wuk7EkqUncOQzZUXQzdrQUJnTG9eTL7u4edhmt8zulvhBdrzKOU9bDXFPwN3Ctd5wp6hky0MFcRB77HEKu59DGw_4eVhgouDen4UViezmrBzRbJIb8hdl48WlkCPHHN9PG1BEcASV1S2rzjiYuC3wB4_BzBpY7fltqNENVM6PoojN8NbGO=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQWJpL56Utnoy5_ltXb-dSvVWrn5kntBV1N2mX4Lb6kekiJWZvWJglSc2E72gommU77ec4H2-PpmFxIola7JSDgm-2-C1NdWfmQSQm_87x-8J5nQp9EV-nzJMZI14RIo6kswQp0wZJCmih5v0JB3hqSgm7ygN8KKn3mlXVw2KXrfgC7x_3HA_tADd_jsYhHCL3sljS5aS6XTPrnY6lzrM6G-nBjcTrGqis42vitK=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQUBwoiDjz3zGy0aHGUt8CL2NoCoLgrctx1PjIGGJiwLnl7KEzSSOZkojCfFchBHoWCE7ahlRNYp6PWRaeq42f0tVtUn9lR4OeJCTjqFqffz4WM7u1Nw1sqDjCsR8e3b8rVZc9E4l0BJQQkCcN5uYh2TjQusXYgHfeenahWG7kXElD9rXBMKfCecmg8_x5jZZ6JY8dQeYnaq0Bc1jiDxkni1cs_MtW6cAiJCo74i_DY=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQWq-EpSiupSWsG34a3Uhc2BNh7SZ1efVXeaYCAkqEj9P_y2y4BG8gBVjYMZOxLOOZOMRh_tsmiWllbylasZzQUnCvl1dI5Fc06BekRc_6SNNL7RHMmht2QjffLMWgjGk3MKclH42FWwTbGuJ03ZO40s9X2EShdLgqPXMkQoEFsmRZ-y3rvQgbLKuBVGRVEs7-LPUCId5O1m6CT4ikGAiNVQJr0IrWDGzyR_rMBy5nE=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQVcBTWXvjIj3FPxfCkVe1BWawQ6hq155Y0T73-5t6wDgSRDQaI9yaMahNBYdSzRCEkEZ889VE76gcfG5qCZ-e52ytKH1C_Ed9aWJFGiHm5ivoqLzMWCcligEKE50NreFXDYWFplrRbL-58mZePDLwr8O8uREkzA0wqGAKM8feRQukGsvuaWattjIi0M7vbmHB8iddiaKeZcMToObKOu6M7E_mQ6palEWA-bbw0J8mE=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQVIaeB-ivwXaLlAiHx3KJFqh_2oFg4alFQuIodt6nW2jLgDFiZrjX6dmYyzG3QeNyGoDLZNmRG_30EYgq604lRWNGy7lKX-BtVOcTFInYojVISBioqSwPDxrWARyGuVYAdLVq2WZrinsNGgKXODTrkByQ0AWe_IObFjQxuEoJSzX3dNqrZpFihaDL_tontLSOYXQkotwJTFKmkw9-YVRSJ3EKsrEsIDZK9avj2Dm9k=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQWHS8ZXtLZNz77zyB6BeaNtmxB4Hy2G3Jj5WQbCaHL8AdHlXmmoeDmqnjrbicCqJcRvH8C5m-I-DZVxxeNzIXhvVzL59s1IodNRzCySs0QaTzuxcCqNt7Nk_N2J9pIuQlbcD-0W87urXR7fBjuqCyy29opaLMqVbxdQ28keDJlWePuEL76juTtuXaJFWpw9KaqBqNPfftiDbDquKxFU7wj0cSJvpTcaxtuZqhVL0Jo=w1280',
 'https://lh3.googleusercontent.com/sitesv/AG8ngQV4VSrFWsyBunvQhDzfvCBayi7tmObciFXwhWTELMwoWy4FqAAW_gUfhyYaX0-8LcmYDmN_8A8rTDSu3UPJQk8xOtbVtPjzArVdfUHCyW65JWlGUXZmDVHTQ8Vl_AVf7_-qh7ifBgt9rMMcsx8sVHgTJ4X3aSBgFWI-0OfSfu8AmvZWiAP2Walxkb0vNxaisRn7M0IDmwAp5cHtGc1S6x34X1o7R4NYXPS8qH49myw=w1280'
];
const todoSections={
 'local-area':['Local Area','Explore Ballymoney, Gorey and the Wexford coastline.'],
 transport:['Local Transport','Local Bus: McGoverns Main St to Hughes Ballymoney, 5 mins, €5. Gorey Bus Links: http://www.goreybuslinks.ie/. Taxi Paddy: 0879502031; Chris Bolton: 0876009785. Travel from Dublin by Irish Rail to Gorey or Wexford Bus from Leeson Street.'],
 'walks-trails-greenways':['Beaches, Walks, Trails & Greenways','Walk maps: https://wexfordwalkingtrail.ie/trails-maps/. Four beaches are within five minutes’ drive. Local favourites include Sea Road Ballymoney North, Kiltennel Beach & Forest Walk and Courtown Harbour. Curracloe is around 20 minutes away. Courtown to Ballymoney Loop is 22km.'],
 'take-aways':['Take Aways','A wide range of take-aways is available in Gorey. Orphan Girl Chipper: (053) 942 5308; open weekends in winter and daily in summer from 5pm. Just Eat has current delivery choices. Our favourite Indian is Masala House; our favourite Chinese is Ipho.'],
 'outdoor-activities':['Outdoor Activities','The gated community has two tennis courts, football and five-a-side pitches, playgrounds, The Shed, Kids Play, dog playground and pedal-kart/bicycle track. Tara Meadows Summer Camp runs in July and August. Active Tribe in Courtown offers swimming, gym, archery, laser tag, woodland walks, high ropes, climbing and zip line.'],
 'indoor-activities':['Indoor Activities','Pirates Cove offers bowling and arcades. Movies @ Gorey is nine minutes away. Family options include Kid Zone, Courtown Adventure & Leisure Centre, Amber Springs and Active Tribe classes.'],
 'swimming-pools':['Swimming Pools','Active Tribe, Courtown Leisure Centre (nine minutes by car), Amber Springs (ten minutes), Seafield Spa & Resort (adults only; four minutes) and Ashdown Park Hotel & Leisure Club (seven minutes).'],
 'farms-petting-zoos':['Farms & Petting Zoos','Kia Ora Mini Farm is nine minutes away. Amber Springs includes a petting zoo. Alpaca Lodge offers alpaca feeding and walks. Wexford Lavender Farm has a café, gift shop, playground and woodland walks.'],
 'local-markets-shopping':['Local Markets & Shopping','Gorey Farmers Market: Saturdays 9am–2pm, Esmonde Street. Samhradh Market: Wednesdays, seasonal. Hughes on Ballymoney Road is the closest shop; Gorey is ten minutes away and has supermarkets, retail parks, independent shops and more.'],
 'local-pubs-restaurants':['Local Pubs, Restaurants & Dog Friendly','The Orphan Girl is our closest pub, an eight-minute walk, known for steaks, music and summer outdoor dining. Tara Vale is six minutes by car. Favourites include Seafield’s Clubhouse, The Duck at Marlfield House and Springmount.'],
 'estate-homes-gardens':['Estate Homes & Gardens','Wells House & Gardens has 450 acres of woodland, gardens, fairy and Gruffalo walks, animal farm and playground. Marlfield House & Gardens and The Duck Restaurant are eight minutes away.'],
 golf:['Golf','Ballymoney Golf Club: 053 94 21976 · info@ballymoneygolfclub.ie · http://www.ballymoneygolfclub.ie/. Other local clubs include Tara Glen and Courtown Golf Club.'],
 courtown:['Courtown','Courtown is a ten-minute drive away. Enjoy the amusement park, Pirates Cove, bowling, arcades, soft play, boat rides, train rides, go-karts, woodland trails and harbour walks.'],
 'local-spas':['Local Spas','Seafield Hotel & Spa (adults only), Amber Springs Hotel & Spa and Ashdown Park Hotel all have excellent spa or leisure facilities. Gorey also has several Thai massage options.'],
 'our-favorite-places':['Our Favorite Places','Orphan Girl for Guinness, steak and stone-baked pizzas; Joannes for bread; Salt Rock Dairy for milk and ice cream; Gorey Farmers Market for local produce; and Rowantree Restaurant at Ashdown Park Hotel.']
};

function shell(content) {
  return `<header><a class="brand" href="/the-house">Country Beach Escape</a><button class="menu" aria-label="Toggle menu">☰</button><nav>${nav.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</nav></header><main>${content}</main><footer>Gated Community Country Beach Escape</footer>`;
}
const button = (label, href=booking) => `<a class="button" href="${href}" target="_blank" rel="noreferrer">${label}</a>`;
function home(){return `
  <section class="hero"><div><h1>Gated Community<br>Country Beach Escape</h1><p>A much loved &amp; enjoyed 4 Bed home from home in the beauty of Ballymoney, Gorey, Co. Wexford</p>${button('Book Direct')}</div></section>
  <section class="feature"><h2>Thanks to Chalk &amp; Cheese Travels<br>for featuring us!</h2><p><a href="https://www.instagram.com/chalkandcheesetravels/" target="_blank">@chalkandcheesetravels</a></p><iframe src="https://www.youtube.com/embed/h1V904Dt3JM" title="Chalk & Cheese Travels" allowfullscreen></iframe></section>
  <section class="feature soft"><h2>See our new Cheesy Video to get a feel of your stay at Country Beach Escape!</h2><p>Pack your bags, hit the coast for the place we love the most!</p><iframe src="https://www.youtube.com/embed/TSq83g_t_f8" title="Country Beach Escape video" allowfullscreen></iframe><p>${button('Airbnb Page',airbnb)} ${button('Book Direct')}</p></section>
  <section class="reservations"><h2>Reservations</h2><p>See <a href="${airbnb}">Airbnb Page</a> for the most up to date availability and rates.</p><p>For <strong>SIGNIFICANTLY LOWER nightly rates</strong>, <a href="${booking}">Enquire Here or Book Direct.</a></p><p>WhatsApp or Phone Julianne: <a href="tel:+353868215176">0868215176</a></p></section>
  <section class="quotes"><blockquote>“‘Ghostis’ is the Indo–European root and it describes neither the host nor the guest but the relationship between the two. Hospitality is the space of possibility that opens up between guest and host when both parties willingly engage in this precarious mutual trust.”<cite>Visser, 1991, p.91</cite></blockquote><blockquote>“Fab communication, beautiful house, everything you could ever need.”<cite>Happy Guest</cite></blockquote><blockquote>“Stayed here just last night. And we absolutely loved it. It is a perfect combination of home away from home, yet the luxury of a hotel stay.”<cite>Happy Guest</cite></blockquote></section>`}
function faq(){const qs=['Where are you located?','Where is your nearest shop?','How do I book?','How close is your nearest beach?','How many bedrooms are there?','Is it a comfortable space for a large group?','How many cars can be parked at your property?','What are the check in / out times?','Is the hot tub available all year?','How do you accommodate Children?','I like to cook, how well equipped is your kitchen?','Are pets allowed?'];return `<section class="page narrow"><h1>FAQ</h1>${qs.map(q=>`<details><summary>${q}</summary><p>Please contact Julianne directly for the latest details and to tailor your stay.</p></details>`).join('')}</section>`}
function calendar(){return `<section class="page narrow"><h1>Calendar</h1><iframe class="calendar" src="https://www.google.com/calendar/embed?color=%23a47ae2&mode=month&showCalendars=1&showPrint=0&showTz=0&src=oqla229439rkclp3dq77vuartevnao5g@import.calendar.google.com" title="Availability calendar"></iframe><p>The availability shown below reflects our Airbnb allocation only.</p><p>For the widest choice of dates and our best available rates, we recommend contacting us directly. We'll personally check availability and provide a tailored quotation for your stay.</p><h2>Booking directly</h2><ul><li>Save over 10%, 12% for returning guests.</li><li>No Airbnb service fees</li><li>Early check in when available</li><li>Late check out when available</li></ul><p>We look forward to welcoming you to Country Beach Escape.</p>${button('Enquire')}</section>`}
function galleryPage(){return `<section class="page"><h1>Gallery</h1><div class="gallery">${gallery.map((src,i)=>`<img loading="lazy" src="${src}" alt="Country Beach Escape photo ${i+1}">`).join('')}</div></section>`}
function todo(){return `<section class="todo-landing"><div class="todo-intro"><p class="eyebrow">COUNTRY BEACH ESCAPE</p><h1>Get to know the area a little...</h1><p>Handpicked ideas for days out, eating out, family fun and local essentials.</p></div><div class="todo-grid">${Object.entries(todoSections).map(([slug,[title]])=>`<a href="/to-do/${slug}"><span>Explore</span><strong>${title}</strong><b>→</b></a>`).join('')}<a href="https://www.google.com/maps/contrib/105320640410851453895/reviews/@52.6969146,-6.3552974,11z/data=!4m3!8m2!3m1!1e1?entry=ttu" target="_blank"><span>Explore</span><strong>Our Reviews of local spots</strong><b>→</b></a></div></section>`}
function todoDetail(slug){const item=todoSections[slug];if(!item)return todo();return `<section class="page todo-detail"><a class="back" href="/to-do">← All local guides</a><p class="eyebrow">LOCAL GUIDE</p><h1>${item[0]}</h1>${item[1].split(/(?<=\.)\s+/).map(p=>`<p>${p}</p>`).join('')}<p>${button('Book Direct')}</p></section>`}
function contact(){return `<section class="page contact"><h1>Location</h1><iframe class="map" src="https://maps-api-ssl.google.com/maps?hl=en-US&ll=52.672587,-6.224395&output=embed&q=The+Meadows,+Prospect,+Co.+Wexford,+Ireland+(The+Meadows)&z=14" title="Map"></iframe><h2>Contact us</h2><p>Phone during business hours GMT please</p><p><a href="mailto:countrybeachescape@gmail.com">countrybeachescape@gmail.com</a><br><a href="tel:+353868215176">0868215176</a></p><p><a href="https://g.page/r/Ca0lEk5jBtIqEAE/review">Google Review us</a></p><h2>Book us</h2><p>See our Airbnb page for the most up to date availability and rates. Booking direct will usually be significantly less.</p><p>Credit Cards Accepted</p>${button('Book Direct')}</section>`}
function owner(){return `<section class="page narrow"><h1>Meet the owner</h1><h2>Julianne Hickey</h2><p>Qualified in BSc Hospitality Management in 2002 and holds a post graduate IT Teachers Diploma. Organised with excellent interpersonal skills, highly regarded by colleagues, students and employers. I have been working in the hospitality industry since 1995. Began in our 13 bedroom family guesthouse in Ranelagh in 1995 and from 2017–2020 managed a short let apartment in Dublin with a Booking.com review score of 9.6/10 after over 100 reviews. Happy to share our new family holiday home with others from around the world so they too can enjoy its fantastic energy, comfort and light filled rooms.</p><p>I am a proud part time teacher for Liberties College in the heart of the City of Dublin. It is part of a large network of Further Education &amp; Training institutions CityofDublinETB.ie. I teach a wide variety of subjects from Tourism, Airline and Hospitality subjects to Management and IT subjects. Teaching is what I love along with sharing the parenting of 2 children with my husband.</p><blockquote>“Hospitality is the space of possibility that opens up between guest and host when both parties willingly engage in this precarious mutual trust.”</blockquote><p>Looking forward to hosting you!</p></section>`}
const paths={'/':home,'/the-house':home,'/faq':faq,'/calendar':calendar,'/gallery':galleryPage,'/to-do':todo,'/contact-us':contact,'/owner':owner};
const todoMatch=location.pathname.match(/^\/to-do\/([^/]+)$/);
document.querySelector('#app').innerHTML=shell(todoMatch?todoDetail(todoMatch[1]):(paths[location.pathname]||home)());
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));
